
services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    environment:
      - DATABASE_URL=postgres://soumo:password@account_db/microservice?sslmode=disable
    restart: on-failure

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      - DATABASE_URL=http://catalog_db:9200
    restart: on-failure

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - order_db
    environment:
      - DATABASE_URL=postgres://soumo:password@order_db/microservice?sslmode=disable
      - ACCOUNT_SERVICE=account:8080
      - CATALOG_SERVICE=catalog:8080
    restart: on-failure

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - account
      - catalog
    environment:
      - ACCOUNT_SERVICE=account:8080
      - CATALOG_SERVICE=catalog:8080
      - ORDER_SERVICE=order:8080
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_USER=soumo
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - ES_JAVA_OPTS=-Xmslg -Xmxlg
      - discovery.type=single-node

  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_USER=soumo
      - POSTGRES_PASSWORD=password
    restart: unless-stopped
